version: '3.7'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_desafio
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - network_desafio
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_flask
    # volumes:
    #   - ./:/app
    depends_on:
      - postgres_db
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - network_desafio

volumes:
  postgres_data:

networks:
  network_desafio:
    driver: bridge
